from pydantic import BaseModel, Field
from typing import List, Union, Dict, Annotated

from app.api.schemas.workflow import OutputDataset, CollectionOutputDataset


class ToolExecutionResponse(BaseModel):
    """The result of a tool execution job."""
    state: str = Field(..., description="The final state of the Galaxy job (e.g., 'ok', 'error').")
    outputs: List[
                Annotated[
                        Union[OutputDataset, CollectionOutputDataset],
                        Field(discriminator="type")
                    ]
                ] = Field(..., description="A list of datasets generated by the tool.")
    message: Dict = Field(..., description = "Job execution response messages from galaxy.")