from pydantic import BaseModel, Field
from typing import List, Union, Annotated

from app.api.schemas.workflow import OutputDataset, CollectionOutputDataset


class ToolExecutionResponse(BaseModel):
    """The result of a tool execution job."""
    state: str = Field(..., description="The final state of the Galaxy job (e.g., 'ok', 'error').")
    outputs: List[
                Annotated[
                        Union[OutputDataset, CollectionOutputDataset],
                        Field(discriminator="type")
                    ]
                ] = Field(..., description="A list of datasets generated by the tool.")
    stdout: str | None = None
    stderr: str | None = None
    error_message: str | None = Field(None, description="The error message if the job failed.")